apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240201020857.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240201020857.0.0+build.02e9424
  releaseNotes: |
    Release v20240201020857.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-02-2024-01-35-47-956780359/where-for-dinner-search-my-apps-bundle@sha256:88b478c6aa345ef1f74722e2814d55d3ae9f7a444d9d047c255baba312a11378
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

