apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240201165525.0.0+build.c5ac160
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240201165525.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165525.0.0+build.c5ac160 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-02-2024-01-35-47-956780359/where-for-dinner-ui-my-apps-bundle@sha256:0dff2a5c6b1ca69aea51edcd1cdf02a9a66a40667dbb7bf30eb2886bcfda4a5c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

