apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240201170004.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240201170004.0.0+build.6aff574
  releaseNotes: |
    Release v20240201170004.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-02-2024-01-35-47-956780359/where-for-dinner-my-apps-bundle@sha256:4dffe307abe962761fd89676fcae2dfd63d89ae3c471bc9e871e4be31f75ccf3
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

