apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240201165500.0.0+build.c5ac160
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240201165500.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165500.0.0+build.c5ac160 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-02-2024-01-35-47-956780359/where-for-dinner-notify-my-apps-bundle@sha256:d1d2ae652c6136f8edf3aa632df14e8a004e6a7d6b07d187aff322d7d0a79fb2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

